spring:
  application:
    name: dbtest
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
